name: "Bug report 🐛"
description: Report errors or unexpected behavior
title: "Bug: "
labels:
  - bug
  - backlog

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! Before submitting, please make sure to [search through existing issues](https://github.com/microsoft/industry).

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: Please share with us the step(s) required to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: If possible, please share the error message that you received.
      placeholder: Error Messages
      render: json
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, please include screenshots and paste them into the markdown editor below.
      placeholder: Screenshots
    validations:
      required: false

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone must abide by it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: markdown
    attributes:
      value: "Thanks for completing this form!"
