name: "Documentation Issue 📚"
description: Report issues in our documentation
title: "Documentation: "
labels:
  - documentation
  - backlog

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! Before submitting, please make sure to [search through existing issues](https://github.com/microsoft/industry).

  - type: textarea
    id: description
    attributes:
      label: Documentation Issue
      placeholder: Please share the name of the document along with supporting points on why it requires an amendment.
    validations:
      required: true

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone must abide by it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: markdown
    attributes:
      value: "Thanks for completing this form!"
